[tool.poetry]
name = "tibberios"
version = "0.1.0"
description = "Do awesome stuff with the Tibber API"
authors = ["Lef Filippakis <Lef-F@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
pyTibber = "^0.25.2"

[tool.poetry.group.dev.dependencies]
pandas = "^1.4.4"
matplotlib = "^3.6.0"
plotly = "^5.10.0"
jupyterlab = "^3.4.7"
black = "^22.8.0"

[tool.poetry.scripts]
tibberios = 'tibberios.cli:run'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
