{
 "title": "Home Electricity Monitoring",
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   { "name": "price_agg", "label": "Price Aggregation", "query": "Hourly, Daily, Monthly" },
   {
    "name": "metrics",
    "label": "Electricity Metrics",
    "query": "Consumption : consumption,Spot Price : unit_price,Cost : total_cost"
   }
  ]
 },
 "panels": [
  {
   "title": "Price of Electricity Now",
   "type": "table",
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.home.currentSubscription.priceInfo.current",
     "endTimePath": "endTime",
     "queryText": "query{\n  viewer{\n    home(id:\"\"){\n      currentSubscription{\n        priceInfo{\n          current{\n            startsAt\n            total\n            level\n          }\n        }\n      }\n    }\n  }\n}",
     "timePath": "startsAt"
    }
   ]
  },
  {
   "title": "Electricity Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencySEK" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "queryText": "select\n  avg(total_cost) as \"Average\"\n  , min(total_cost) as \"Min\"\n  , max(total_cost) as \"Max\"\n  , sum(total_cost) as \"Total\"\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000\n\n",
     "rawQueryText": "select\n  avg(total_cost) as \"Average\"\n  , min(total_cost) as \"Min\"\n  , max(total_cost) as \"Max\"\n  , sum(total_cost) as \"Total\"\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000\n\n"
    }
   ]
  },
  {
   "title": "Electricity Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencySEK" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "queryText": "select\n  avg(unit_price) as \"Average\"\n  , min(unit_price) as \"Min\"\n  , max(unit_price) as \"Max\"\n  , sum(unit_price) as \"Total\"\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000",
     "rawQueryText": "select\n  avg(unit_price) as \"Average\"\n  , min(unit_price) as \"Min\"\n  , max(unit_price) as \"Max\"\n  , sum(unit_price) as \"Total\"\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000"
    }
   ]
  },
  {
   "title": "Electricity Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "queryText": "select\n  avg(consumption) as \"Average\"\n  , min(consumption) as \"Min\"\n  , max(consumption) as \"Max\"\n  , sum(consumption) as \"Total\"\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000",
     "rawQueryText": "select\n  avg(consumption) as \"Average\"\n  , min(consumption) as \"Min\"\n  , max(consumption) as \"Max\"\n  , sum(consumption) as \"Total\"\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000"
    }
   ]
  },
  {
   "title": "Daily Energy Consumption and Price",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 3 },
   "targets": [
    {
     "queryText": "select \n  case\n    when '${price_agg}' = 'Hourly' \n      then unixepoch(start_time)\n    when '${price_agg}' = 'Daily' \n      then unixepoch(start_time, 'start of day')\n    when '${price_agg}' = 'Monthly' \n      then unixepoch(start_time, 'start of month')\n  end as start_time\n  , avg(unit_price) as unit_price\n  , avg(total_cost) as total_cost\n  , avg(consumption) as consumption\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000\ngroup by 1\norder by 1\n\n",
     "rawQueryText": "select \n  case\n    when '${price_agg}' = 'Hourly' \n      then unixepoch(start_time)\n    when '${price_agg}' = 'Daily' \n      then unixepoch(start_time, 'start of day')\n    when '${price_agg}' = 'Monthly' \n      then unixepoch(start_time, 'start of month')\n  end as start_time\n  , avg(unit_price) as unit_price\n  , avg(total_cost) as total_cost\n  , avg(consumption) as consumption\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000\ngroup by 1\norder by 1\n\n",
     "timeColumns": [ "start_time" ]
    }
   ]
  },
  {
   "title": "Daily Average Price",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencySEK" } },
   "targets": [
    {
     "queryText": "select\n  unixepoch(date(start_time)) as start_date\n  , avg(unit_price) as avg_price\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) < $__to / 1000\ngroup by 1\norder by 1\n",
     "rawQueryText": "select\n  unixepoch(date(start_time)) as start_date\n  , avg(unit_price) as avg_price\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) < $__to / 1000\ngroup by 1\norder by 1\n",
     "timeColumns": [ "start_date" ]
    }
   ]
  },
  {
   "title": "Cumulative Energy Consumption and Cost",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "with aggregation as (\n  select\n    case\n      when '${price_agg}' = 'Hourly' \n        then unixepoch(start_time)\n      when '${price_agg}' = 'Daily' \n        then unixepoch(start_time, 'start of day')\n      when '${price_agg}' = 'Monthly' \n        then unixepoch(start_time, 'start of month')\n    end as start_time\n    , sum(total_cost) as total_cost\n    , sum(consumption) as consumption\n  from consumption\n  where unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000\n  group by 1\n)\n\nselect \n  start_time\n  , sum(total_cost) over (order by start_time) as cumulative_cost\n  , sum(consumption) over (order by start_time) as cumulative_consumption\nfrom aggregation\norder by 1\n\n",
     "rawQueryText": "with aggregation as (\n  select\n    case\n      when '${price_agg}' = 'Hourly' \n        then unixepoch(start_time)\n      when '${price_agg}' = 'Daily' \n        then unixepoch(start_time, 'start of day')\n      when '${price_agg}' = 'Monthly' \n        then unixepoch(start_time, 'start of month')\n    end as start_time\n    , sum(total_cost) as total_cost\n    , sum(consumption) as consumption\n  from consumption\n  where unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000\n  group by 1\n)\n\nselect \n  start_time\n  , sum(total_cost) over (order by start_time) as cumulative_cost\n  , sum(consumption) over (order by start_time) as cumulative_consumption\nfrom aggregation\norder by 1\n\n",
     "timeColumns": [ "start_time" ]
    }
   ]
  },
  {
   "title": "Distribution of ${metrics:text}",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "repeat": "metrics",
   "fieldConfig": { "defaults": { "unit": "currencySEK" } },
   "targets": [
    {
     "queryText": "select ${metrics:value}\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000",
     "rawQueryText": "select ${metrics:value}\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000"
    }
   ]
  },
  {
   "title": "Prices from Now to Tomorrow",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencySEK" } },
   "targets": [
    {
     "queryText": "select \n  unixepoch(start_time) as start_time\n  , unit_price\nfrom consumption\nwhere unixepoch(start_time) >= unixepoch(strftime('%Y-%m-%dT%H:00:00', 'now')) and unixepoch(start_time) <= unixepoch('now','+2 day')\n\n",
     "rawQueryText": "select \n  unixepoch(start_time) as start_time\n  , unit_price\nfrom consumption\nwhere unixepoch(start_time) >= unixepoch(strftime('%Y-%m-%dT%H:00:00', 'now')) and unixepoch(start_time) <= unixepoch('now','+2 day')\n\n",
     "timeColumns": [ "start_time" ]
    }
   ]
  },
  {
   "title": "Average ${metrics:text} per Hour of the Day",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "repeat": "metrics",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "select \n  strftime('%H', start_time) as \"Hour of the Day\"\n  , avg(${metrics:value}) as \"Average ${metrics:text}\"\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000\ngroup by 1",
     "rawQueryText": "select \n  strftime('%H', start_time) as \"Hour of the Day\"\n  , avg(${metrics:value}) as \"Average ${metrics:text}\"\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000\ngroup by 1"
    }
   ]
  },
  {
   "title": "Average ${metrics:text} per Day of the Week",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "repeat": "metrics",
   "fieldConfig": { "defaults": { "unit": "currencySEK" } },
   "targets": [
    {
     "queryText": "select \n  case\n    when strftime('%w', start_time) = '0' then 'Sunday'\n    when strftime('%w', start_time) = '1' then 'Monday'\n    when strftime('%w', start_time) = '2' then 'Tuesday'\n    when strftime('%w', start_time) = '3' then 'Wednesday'\n    when strftime('%w', start_time) = '4' then 'Thursday'\n    when strftime('%w', start_time) = '5' then 'Friday'\n    when strftime('%w', start_time) = '6' then 'Saturday'\n  end as \"Day of the Week\"\n  , avg(${metrics:value}) as \"Average ${metrics:text}\"\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000\ngroup by 1",
     "rawQueryText": "select \n  case\n    when strftime('%w', start_time) = '0' then 'Sunday'\n    when strftime('%w', start_time) = '1' then 'Monday'\n    when strftime('%w', start_time) = '2' then 'Tuesday'\n    when strftime('%w', start_time) = '3' then 'Wednesday'\n    when strftime('%w', start_time) = '4' then 'Thursday'\n    when strftime('%w', start_time) = '5' then 'Friday'\n    when strftime('%w', start_time) = '6' then 'Saturday'\n  end as \"Day of the Week\"\n  , avg(${metrics:value}) as \"Average ${metrics:text}\"\nfrom consumption\nwhere unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) <= $__to / 1000\ngroup by 1"
    }
   ]
  }
 ]
}