{
 "title": "How Much Things Cost?",
 "time": { "from": "now", "to": "now+2d" },
 "templating": {
  "list": [
   {
    "name": "kwh",
    "label": "Activity",
    "query": "Charge Car 0-100% : 46, Charge Car Hourly : 3.7, Computer Screen Average : 0.015 , Computer Screen w/ USB-C Charger : 0.118 , MacBook Pro : 0.140 , Night Light : 0.002"
   },
   { "name": "price_agg", "label": "Price Aggregation", "query": "Hourly, Daily, Weekly, Monthly" }
  ]
 },
 "panels": [
  {
   "title": "Total cost of continuous operation for ${kwh:text}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencySEK" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "with prices as (\n  SELECT \n      case\n        when '${price_agg}' = 'Hourly' \n          then unixepoch(strftime('%Y-%m-%dT%H:00:00', start_time))\n        when '${price_agg}' = 'Daily' \n          then unixepoch(start_time, 'start of day')\n        when '${price_agg}' = 'Weekly' \n          then strftime('%W', start_time)\n        when '${price_agg}' = 'Monthly' \n          then unixepoch(start_time, 'start of month')\n      end as start_time\n    , unit_price * ${kwh} as hour_price\n    , 1 as consecutive_hours\n  FROM consumption\n  WHERE unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) < $__to / 1000\n)\nselect\n  sum(hour_price) as \"Total Cost\"\n  , sum(consecutive_hours) as \"Total Hours\"\nfrom prices",
     "rawQueryText": "with prices as (\n  SELECT \n      case\n        when '${price_agg}' = 'Hourly' \n          then unixepoch(strftime('%Y-%m-%dT%H:00:00', start_time))\n        when '${price_agg}' = 'Daily' \n          then unixepoch(start_time, 'start of day')\n        when '${price_agg}' = 'Weekly' \n          then strftime('%W', start_time)\n        when '${price_agg}' = 'Monthly' \n          then unixepoch(start_time, 'start of month')\n      end as start_time\n    , unit_price * ${kwh} as hour_price\n    , 1 as consecutive_hours\n  FROM consumption\n  WHERE unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) < $__to / 1000\n)\nselect\n  sum(hour_price) as \"Total Cost\"\n  , sum(consecutive_hours) as \"Total Hours\"\nfrom prices",
     "timeColumns": [ "start_time" ]
    }
   ]
  },
  {
   "title": "Price of Electricity Now",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "viewer.home.currentSubscription.priceInfo.current",
     "endTimePath": "endTime",
     "queryText": "query{\n  viewer{\n    home(id:\"your-home-id-here\"){\n      currentSubscription{\n        priceInfo{\n          current{\n            total\n            level\n          }\n        }\n      }\n    }\n  }\n}"
    }
   ]
  },
  {
   "title": "${kwh:text} | Cost over each hour bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencySEK" } },
   "targets": [
    {
     "queryText": "SELECT\n  case\n    when '${price_agg}' = 'Hourly' \n      then unixepoch(strftime('%Y-%m-%dT%H:00:00', start_time))\n    when '${price_agg}' = 'Daily' \n      then unixepoch(start_time, 'start of day')\n    when '${price_agg}' = 'Weekly' \n      then strftime('%W', start_time)\n    when '${price_agg}' = 'Monthly' \n      then unixepoch(start_time, 'start of month')\n  end as start_time\n  , avg(unit_price * ${kwh}) as hour_price\nFROM consumption\nWHERE unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) < $__to / 1000\ngroup by 1\norder by 1",
     "rawQueryText": "SELECT\n  case\n    when '${price_agg}' = 'Hourly' \n      then unixepoch(strftime('%Y-%m-%dT%H:00:00', start_time))\n    when '${price_agg}' = 'Daily' \n      then unixepoch(start_time, 'start of day')\n    when '${price_agg}' = 'Weekly' \n      then strftime('%W', start_time)\n    when '${price_agg}' = 'Monthly' \n      then unixepoch(start_time, 'start of month')\n  end as start_time\n  , avg(unit_price * ${kwh}) as hour_price\nFROM consumption\nWHERE unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) < $__to / 1000\ngroup by 1\norder by 1",
     "timeColumns": [ "start_time" ]
    }
   ]
  },
  {
   "title": "${kwh:text} | Cost of continuous operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencySEK" } },
   "targets": [
    {
     "queryText": "with prices as (\n  SELECT \n      case\n        when '${price_agg}' = 'Hourly' \n          then unixepoch(strftime('%Y-%m-%dT%H:00:00', start_time))\n        when '${price_agg}' = 'Daily' \n          then unixepoch(start_time, 'start of day')\n        when '${price_agg}' = 'Weekly' \n          then strftime('%W', start_time)\n        when '${price_agg}' = 'Monthly' \n          then unixepoch(start_time, 'start of month')\n      end as start_time\n    , unit_price * ${kwh} as hour_price\n  FROM consumption\n  WHERE unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) < $__to / 1000\n)\nselect distinct\n  start_time\n  , sum(hour_price) over (order by start_time) as cum_hour_price\nfrom prices\norder by 1",
     "rawQueryText": "with prices as (\n  SELECT \n      case\n        when '${price_agg}' = 'Hourly' \n          then unixepoch(strftime('%Y-%m-%dT%H:00:00', start_time))\n        when '${price_agg}' = 'Daily' \n          then unixepoch(start_time, 'start of day')\n        when '${price_agg}' = 'Weekly' \n          then strftime('%W', start_time)\n        when '${price_agg}' = 'Monthly' \n          then unixepoch(start_time, 'start of month')\n      end as start_time\n    , unit_price * ${kwh} as hour_price\n  FROM consumption\n  WHERE unixepoch(start_time) >= $__from / 1000 and unixepoch(start_time) < $__to / 1000\n)\nselect distinct\n  start_time\n  , sum(hour_price) over (order by start_time) as cum_hour_price\nfrom prices\norder by 1",
     "timeColumns": [ "start_time" ]
    }
   ]
  }
 ]
}